-- The four study kinds from the specification, the sharing of collections and
-- the uniqueness of "Mis partidas".
--
-- See constants/platform/study-codes.const.ts (the catalog) and
-- services/studies/study-rules.ts (what can be done with each kind).

-- ---------------------------------------------------------------------------
-- 1. DatabaseKind catalog: "Torneo" comes in, "Repertorio" goes out
-- ---------------------------------------------------------------------------

-- "Torneo" groups the games the student played in one competition.
INSERT INTO "DatabaseKind" ("code", "label", "order")
VALUES ('TOURNAMENT', 'Torneo', 1)
ON CONFLICT ("code") DO UPDATE SET "label" = EXCLUDED."label", "order" = EXCLUDED."order";

-- The catalog's order is the specification's and it is read by the "new study"
-- dropdown, so the rest is repositioned.
UPDATE "DatabaseKind" SET "order" = 0 WHERE "code" = 'MY_GAMES';
UPDATE "DatabaseKind" SET "order" = 2 WHERE "code" = 'STUDY';
UPDATE "DatabaseKind" SET "order" = 3 WHERE "code" = 'COLLECTION';

-- "Repertorio" is not one of the four kinds. The databases that had it move to
-- "Estudio", which is what they are — material the student gathers to analyse —;
-- that way the DELETE that follows cannot clash with a foreign key.
UPDATE "GameDatabase"
   SET "kindId" = (SELECT "id" FROM "DatabaseKind" WHERE "code" = 'STUDY')
 WHERE "kindId" = (SELECT "id" FROM "DatabaseKind" WHERE "code" = 'REPERTOIRE');

DELETE FROM "DatabaseKind" WHERE "code" = 'REPERTOIRE';

-- ---------------------------------------------------------------------------
-- 2. Sharing of collections
-- ---------------------------------------------------------------------------

CREATE TABLE "StudyShare" (
    "id" TEXT NOT NULL,
    "databaseId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "teacherId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "StudyShare_pkey" PRIMARY KEY ("id")
);

-- A collection is shared with several students, but with each one only once.
CREATE UNIQUE INDEX "StudyShare_databaseId_userId_key" ON "StudyShare"("databaseId", "userId");

-- For the hot query: "which collections have been shared with me", which goes
-- into the visibility filter of Mis estudios and of the position search.
CREATE INDEX "StudyShare_userId_idx" ON "StudyShare"("userId");

ALTER TABLE "StudyShare" ADD CONSTRAINT "StudyShare_databaseId_fkey"
  FOREIGN KEY ("databaseId") REFERENCES "GameDatabase"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StudyShare" ADD CONSTRAINT "StudyShare_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StudyShare" ADD CONSTRAINT "StudyShare_teacherId_fkey"
  FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- 3. "Mis partidas": one per student, and nobody without one
-- ---------------------------------------------------------------------------

-- Accounts created before creation made one on its own. `nanoid(8)` is
-- generated by Prisma on the client and there is no client here, so the id is
-- composed with md5() of the user's id trimmed to eight: it is deterministic
-- — rerunning the migration duplicates nothing — and from the same alphabet as
-- the others.
INSERT INTO "GameDatabase" ("id", "ownerTypeId", "userId", "name", "description", "kindId", "isDefault", "order", "createdAt", "updatedAt")
SELECT
    substr(md5('my-games:' || u."id"), 1, 8),
    (SELECT "id" FROM "OwnerType" WHERE "code" = 'USER'),
    u."id",
    'Mis partidas',
    'Tus partidas que no pertenecen a ningún torneo.',
    (SELECT "id" FROM "DatabaseKind" WHERE "code" = 'MY_GAMES'),
    true,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM "User" u
WHERE NOT EXISTS (
    SELECT 1 FROM "GameDatabase" d WHERE d."userId" = u."id" AND d."isDefault" = true
);

-- Manual constraint (not expressible in the Prisma schema; see prisma/schema.prisma).
--
-- Exactly one "Mis partidas" per student. Account creation makes it and nobody
-- else ever makes one, but two simultaneous creations would both pass any check
-- in code and only the index separates them.
CREATE UNIQUE INDEX "game_database_one_default_per_user"
  ON "GameDatabase" ("userId") WHERE "isDefault" = true;
