import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import { chessGlyph, gramatika, suisseIntl } from "./fonts";
import { GoogleAnalytics } from "@/components/common/google-analytics.comp";
import { MetaPixel } from "@/components/common/meta-pixel.comp";
import { SITE_URL } from "@/lib/site-url";

// `metadataBase` is what lets each page's canonical and Open Graph image be
// relative paths. The default OG image is generated by `opengraph-image.tsx`
// (this same segment) and inherited by every public page that does not
// declare its own, as the blog does.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "365 Días de Ajedrez | Academia de ajedrez",
  description:
    "Academia de ajedrez en línea con un método progresivo, cursos personalizados y seguimiento para mejorar tu juego.",
  keywords: ["ajedrez", "academia", "entrenamiento", "clases de ajedrez"],
  openGraph: {
    siteName: "365 Días de Ajedrez",
    title: "365 Días de Ajedrez",
    description:
      "Un método progresivo para mejorar tu ajedrez con clases guiadas, seguimiento y recursos de estudio.",
    type: "website",
    locale: "es_MX",
  },
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="es" className={`${gramatika.variable} ${suisseIntl.variable} ${chessGlyph.variable}`}>
      <body>
        <a className="skip-link" href="#contenido">
          Saltar al contenido
        </a>
        {children}
        <GoogleAnalytics />
        <MetaPixel />
        {/* Its script only exists on Vercel deployments; elsewhere (next start
            locally, another host) it produced a console 404 on every visit. */}
        {process.env.VERCEL === "1" && <Analytics />}
      </body>
    </html>
  );
}
