/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    tags: Tag;
    media: Media;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-header': HomeHeader;
    'home-hero': HomeHero;
    'home-program': HomeProgram;
    'home-teacher': HomeTeacher;
    'home-packages': HomePackage;
    'home-faq': HomeFaq;
    'home-mentors': HomeMentors;
    'home-cta': HomeCta;
    'site-settings': SiteSettings;
  };
  globalsSelect: {
    'home-header': HomeHeaderSelect<false> | HomeHeaderSelect<true>;
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'home-program': HomeProgramSelect<false> | HomeProgramSelect<true>;
    'home-teacher': HomeTeacherSelect<false> | HomeTeacherSelect<true>;
    'home-packages': HomePackagesSelect<false> | HomePackagesSelect<true>;
    'home-faq': HomeFaqSelect<false> | HomeFaqSelect<true>;
    'home-mentors': HomeMentorsSelect<false> | HomeMentorsSelect<true>;
    'home-cta': HomeCtaSelect<false> | HomeCtaSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Se genera solo del título. Cambiarlo mueve la URL pública — hazlo con cuidado.
   */
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Se genera solo del título. Cambiarlo mueve la URL pública — hazlo con cuidado.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Se genera solo del título. Cambiarlo mueve la URL pública — hazlo con cuidado.
   */
  slug?: string | null;
  excerpt: string;
  featuredImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | User;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  seo?: {
    /**
     * Si se deja vacío, se usa el título del artículo.
     */
    metaTitle?: string | null;
    /**
     * Si se deja vacío, se usa el excerpt del artículo.
     */
    metaDescription?: string | null;
    /**
     * Si se deja vacío, se usa la imagen destacada.
     */
    ogImage?: (number | null) | Media;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  categories?: T;
  tags?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-header".
 */
export interface HomeHeader {
  id: number;
  navItems?: (NavLinkBlock | NavDropdownBlock)[] | null;
  ctaLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavLinkBlock".
 */
export interface NavLinkBlock {
  label: string;
  href: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'navLink';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavDropdownBlock".
 */
export interface NavDropdownBlock {
  label: string;
  links: {
    label: string;
    href: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'navDropdown';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  title: string;
  description: string;
  image: number | Media;
  cta: {
    label: string;
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-program".
 */
export interface HomeProgram {
  id: number;
  sectionTitle: string;
  sectionDescription: string;
  note?: string | null;
  topicsHeading: string;
  modules: {
    title: string;
    durationLabel: string;
    subtitle?: string | null;
    description: string;
    topics?: string[] | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-teacher".
 */
export interface HomeTeacher {
  id: number;
  eyebrow: string;
  name: string;
  badge: string;
  summary: string;
  photo: number | Media;
  ctaLabel: string;
  stats: {
    value: string;
    label: string;
    id?: string | null;
  }[];
  eloLabel: string;
  eloRatings: {
    label: string;
    value: number;
    id?: string | null;
  }[];
  game: {
    title: string;
    paragraphs: {
      text: string;
      id?: string | null;
    }[];
    /**
     * Ej: "e4 c6 d4 d5 exd5 cxd5..." — sin números de jugada.
     */
    moves: string;
    flipBoard?: boolean | null;
    /**
     * Mapa opcional generado por análisis de motor, ej: { "8b": "best", "13w": "mistake" }.
     */
    annotations?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-packages".
 */
export interface HomePackage {
  id: number;
  sectionTitle: string;
  sectionDescription: string;
  packageOne: {
    name: string;
    price: number;
    previousPrice?: number | null;
    discountPercent?: number | null;
    currency: string;
    period: string;
    description: string;
    features: string[];
    ctaLabel: string;
    ctaUrl: string;
    featured?: boolean | null;
  };
  packageTwo: {
    name: string;
    price: number;
    previousPrice?: number | null;
    discountPercent?: number | null;
    currency: string;
    period: string;
    description: string;
    features: string[];
    ctaLabel: string;
    ctaUrl: string;
    featured?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-faq".
 */
export interface HomeFaq {
  id: number;
  eyebrow: string;
  sectionTitle: string;
  sectionDescription: string;
  ctaLabel: string;
  questions: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-mentors".
 */
export interface HomeMentors {
  id: number;
  eyebrow: string;
  sectionTitle: string;
  sectionDescription: string;
  mentors: {
    slug: string;
    name: string;
    lastName: string;
    city: string;
    birthYear: number;
    gender: 'male' | 'female';
    photo: number | Media;
    photoFocus?: string | null;
    shortDescription: string;
    summary: string;
    fideId: string;
    federation: string;
    standardElo: number;
    rapidElo: number;
    blitzElo: number;
    chessComElo?: number | null;
    shortFideTitle?: ('GM' | 'IM' | 'FM' | 'CM' | 'NM' | 'WGM' | 'WIM' | 'WFM' | 'WCM' | 'WNM') | null;
    longFideTitle?:
      | (
          | 'Grandmaster'
          | 'International Master'
          | 'FIDE Master'
          | 'Candidate Master'
          | 'National Master'
          | 'Woman Grandmaster'
          | 'Woman International Master'
          | 'Woman FIDE Master'
          | 'Woman Candidate Master'
          | 'Woman National Master'
          | 'Instructor · Jugador federado FIDE'
        )
      | null;
    achievements?:
      | {
          year: string;
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    testimonials?:
      | {
          name: string;
          detail: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    featuredGame: {
      gameTitle: string;
      gameText: string;
      gameNote: string;
      moves: string;
      flipBoard?: boolean | null;
    };
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-cta".
 */
export interface HomeCta {
  id: number;
  title: string;
  subtitle: string;
  ctaLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSettings {
  id: number;
  whatsappCountryCode:
    | '52'
    | '1'
    | '34'
    | '502'
    | '504'
    | '503'
    | '505'
    | '506'
    | '507'
    | '57'
    | '58'
    | '593'
    | '51'
    | '591'
    | '56'
    | '54'
    | '598'
    | '595';
  whatsappLocalNumber: string;
  whatsappDefaultMessage: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-header_select".
 */
export interface HomeHeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        navLink?: T | NavLinkBlockSelect<T>;
        navDropdown?: T | NavDropdownBlockSelect<T>;
      };
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavLinkBlock_select".
 */
export interface NavLinkBlockSelect<T extends boolean = true> {
  label?: T;
  href?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavDropdownBlock_select".
 */
export interface NavDropdownBlockSelect<T extends boolean = true> {
  label?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-program_select".
 */
export interface HomeProgramSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionDescription?: T;
  note?: T;
  topicsHeading?: T;
  modules?:
    | T
    | {
        title?: T;
        durationLabel?: T;
        subtitle?: T;
        description?: T;
        topics?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-teacher_select".
 */
export interface HomeTeacherSelect<T extends boolean = true> {
  eyebrow?: T;
  name?: T;
  badge?: T;
  summary?: T;
  photo?: T;
  ctaLabel?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  eloLabel?: T;
  eloRatings?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  game?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        moves?: T;
        flipBoard?: T;
        annotations?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-packages_select".
 */
export interface HomePackagesSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionDescription?: T;
  packageOne?:
    | T
    | {
        name?: T;
        price?: T;
        previousPrice?: T;
        discountPercent?: T;
        currency?: T;
        period?: T;
        description?: T;
        features?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        featured?: T;
      };
  packageTwo?:
    | T
    | {
        name?: T;
        price?: T;
        previousPrice?: T;
        discountPercent?: T;
        currency?: T;
        period?: T;
        description?: T;
        features?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        featured?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-faq_select".
 */
export interface HomeFaqSelect<T extends boolean = true> {
  eyebrow?: T;
  sectionTitle?: T;
  sectionDescription?: T;
  ctaLabel?: T;
  questions?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-mentors_select".
 */
export interface HomeMentorsSelect<T extends boolean = true> {
  eyebrow?: T;
  sectionTitle?: T;
  sectionDescription?: T;
  mentors?:
    | T
    | {
        slug?: T;
        name?: T;
        lastName?: T;
        city?: T;
        birthYear?: T;
        gender?: T;
        photo?: T;
        photoFocus?: T;
        shortDescription?: T;
        summary?: T;
        fideId?: T;
        federation?: T;
        standardElo?: T;
        rapidElo?: T;
        blitzElo?: T;
        chessComElo?: T;
        shortFideTitle?: T;
        longFideTitle?: T;
        achievements?:
          | T
          | {
              year?: T;
              title?: T;
              text?: T;
              id?: T;
            };
        testimonials?:
          | T
          | {
              name?: T;
              detail?: T;
              text?: T;
              id?: T;
            };
        featuredGame?:
          | T
          | {
              gameTitle?: T;
              gameText?: T;
              gameNote?: T;
              moves?: T;
              flipBoard?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-cta_select".
 */
export interface HomeCtaSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  whatsappCountryCode?: T;
  whatsappLocalNumber?: T;
  whatsappDefaultMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: number | Media;
  alt: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  title?: string | null;
  content: string;
  type: 'info' | 'tip' | 'warning';
  id?: string | null;
  blockName?: string | null;
  blockType: 'calloutBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChessDiagramBlock".
 */
export interface ChessDiagramBlock {
  /**
   * Posición en notación FEN.
   */
  fen: string;
  caption?: string | null;
  orientation: 'white' | 'black';
  id?: string | null;
  blockName?: string | null;
  blockType: 'chessDiagramBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChessGameBlock".
 */
export interface ChessGameBlock {
  /**
   * Partida completa en notación PGN.
   */
  pgn: string;
  title?: string | null;
  players?: string | null;
  event?: string | null;
  date?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'chessGameBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}