-- Shortens the identifiers of studies and games, which go in the URL.
--
-- It renames PRIMARY KEYS. It is safe because every foreign key pointing at
-- these two tables is ON UPDATE CASCADE, so the children rewrite themselves:
--   Game.databaseId, GamePosition.databaseId  → GameDatabase.id
--   GamePosition.gameId, ClassBlock.gameId    → Game.id
--
-- There is no schema change: the column was already TEXT without a DEFAULT,
-- because the id is generated by Prisma on the client (uuid() before, nanoid(8) now).

-- 1. The seed's rows, with EXPLICIT renames.
--
-- prisma/seed.ts upserts by these ids. If they were given a random one, the next
-- `npm run db:seed` would not find the rows and would create duplicates, so the
-- literals below have to be exactly those of IDS in prisma/seed-data.ts.
UPDATE "GameDatabase" SET id = 'demoMisP' WHERE id = 'f0000000-0000-4000-8000-000000000001';
UPDATE "GameDatabase" SET id = 'demoAtaq' WHERE id = 'f0000000-0000-4000-8000-000000000002';
UPDATE "GameDatabase" SET id = 'demoSici' WHERE id = 'f0000000-0000-4000-8000-000000000003';

UPDATE "Game" SET id = 'demoOper' WHERE id = 'f1000000-0000-4000-8000-000000000001';
UPDATE "Game" SET id = 'demoInmo' WHERE id = 'f1000000-0000-4000-8000-000000000002';
UPDATE "Game" SET id = 'demoSiem' WHERE id = 'f1000000-0000-4000-8000-000000000003';
UPDATE "Game" SET id = 'demoOpoc' WHERE id = 'f1000000-0000-4000-8000-000000000004';
UPDATE "Game" SET id = 'demoAlap' WHERE id = 'f1000000-0000-4000-8000-000000000005';

-- And those of the course "Piense como un gran maestro", which brings its own
-- seeding module with fixed ids (prisma/seed-courses/think-like-a-grandmaster.ts).
UPDATE "GameDatabase" SET id = 'kotovDb0' WHERE id = 'f0000000-0000-4000-8000-000000000010';

UPDATE "Game" SET id = 'kotovG01' WHERE id = 'f1000000-0000-4000-8000-000000000010';
UPDATE "Game" SET id = 'kotovG02' WHERE id = 'f1000000-0000-4000-8000-000000000011';
UPDATE "Game" SET id = 'kotovG03' WHERE id = 'f1000000-0000-4000-8000-000000000012';
UPDATE "Game" SET id = 'kotovG04' WHERE id = 'f1000000-0000-4000-8000-000000000013';
UPDATE "Game" SET id = 'kotovG05' WHERE id = 'f1000000-0000-4000-8000-000000000014';
UPDATE "Game" SET id = 'kotovG06' WHERE id = 'f1000000-0000-4000-8000-000000000015';
UPDATE "Game" SET id = 'kotovG07' WHERE id = 'f1000000-0000-4000-8000-000000000016';
UPDATE "Game" SET id = 'kotovG08' WHERE id = 'f1000000-0000-4000-8000-000000000017';
UPDATE "Game" SET id = 'kotovG09' WHERE id = 'f1000000-0000-4000-8000-000000000018';
UPDATE "Game" SET id = 'kotovG10' WHERE id = 'f1000000-0000-4000-8000-000000000019';
UPDATE "Game" SET id = 'kotovG11' WHERE id = 'f1000000-0000-4000-8000-000000000020';
UPDATE "Game" SET id = 'kotovG12' WHERE id = 'f1000000-0000-4000-8000-000000000021';
UPDATE "Game" SET id = 'kotovG13' WHERE id = 'f1000000-0000-4000-8000-000000000022';
-- 2. Everything else, with a random id from the same alphabet nanoid uses.
DO $$
DECLARE
  alphabet CONSTANT text := 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  row_id text;
  candidate text;
BEGIN
  FOR row_id IN SELECT id FROM "GameDatabase" WHERE length(id) > 8 LOOP
    LOOP
      candidate := '';
      FOR position IN 1..8 LOOP
        candidate := candidate || substr(alphabet, floor(random() * 62)::int + 1, 1);
      END LOOP;
      -- The primary key would already prevent the clash; checking it here keeps the
      -- migration from failing entirely over a coincidence.
      EXIT WHEN NOT EXISTS (SELECT 1 FROM "GameDatabase" WHERE id = candidate);
    END LOOP;
    UPDATE "GameDatabase" SET id = candidate WHERE id = row_id;
  END LOOP;

  FOR row_id IN SELECT id FROM "Game" WHERE length(id) > 8 LOOP
    LOOP
      candidate := '';
      FOR position IN 1..8 LOOP
        candidate := candidate || substr(alphabet, floor(random() * 62)::int + 1, 1);
      END LOOP;
      EXIT WHEN NOT EXISTS (SELECT 1 FROM "Game" WHERE id = candidate);
    END LOOP;
    UPDATE "Game" SET id = candidate WHERE id = row_id;
  END LOOP;
END $$;
